#!/usr/bin/dh-exec
etc/*
lib/systemd/
[linux-any] lib/udev
lib/*/security/*.so
usr/bin/gdm-screenshot
usr/lib/gdm3/gdm-*
usr/sbin/gdm
usr/share/pixmaps/
usr/share/locale/
usr/share/icons/
usr/share/help/
usr/share/gdm/gdb-cmd
usr/share/gdm/locale.alias
usr/share/gdm/greeter
usr/share/gdm/*.schemas
usr/share/gdm/greeter-dconf-defaults
usr/share/gnome-session/
usr/share/dconf/
var/*

debian/62-Endless-disable-wayland.rules	etc/udev/rules.d
debian/Xsession				etc/gdm3
debian/insserv.conf.d			etc
